version: 3.4.2
jobs:
  build:
    docker:
      - image: barichello/godot-ci
    steps:
      - checkout
      - run: |
          mkdir -p ./build/html
          # mkdir -p ./build/windows
          # mkdir -p ./build/macos
      - run: godot --export HTML5 ./build/html/index.html
